$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: gpu_environment
build:
    path: ../environment_files
    dockerfile_path: Dockerfile
description: GPU runtime environment.
